<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-VetClinicManager-a1666096-75be-42b2-96de-e6f864564ea7</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.5"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.5"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.5"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.5"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5"/>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
        <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.2" />
        <PackageReference Include="QuestPDF" Version="2025.12.4" />
        <PackageReference Include="Riok.Mapperly" Version="4.3.0-next.2" />
        <PackageReference Include="SendGrid" Version="9.29.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Areas\Admin\DTOs\" />
      <Folder Include="wwwroot\uploads\" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="nlog.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
